const randomOptions = [
  [
    "will",
    "will not",
    "might",
    "might not",
    "probably",
    "probably not",
    "possibly",
    "possibly not",
    "presumably",
    "presumably not",
    "may",
    "may not",
  ],
  ["get", "have"],
  [
    "an amazing",
    "an awesome",
    "a great",
    "an excellent",
    "a fabulous",
    "a bad",
    "an odd",
    "an outrageous",
    "a hedious",
    "an awful",
  ],
  [
    "wife",
    "husband",
    "boyfriend",
    "girlfriend",
    "friend",
    "relationship",
    "experience",
    "story to tell",
    "trip",
    "health",
    'car',
    'house',
    'job',
    'surprise',
    'finance status'
  ],
];